version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      POSTGRES_DB: intel
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "intel"]
      interval: 5s
      timeout: 3s
      retries: 10

  neo4j:
    image: neo4j:5.23
    environment:
      NEO4J_AUTH: neo4j/neo4j
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    ports: ["7474:7474", "7687:7687"]
    volumes:
      - neo4jdata:/data

  api:
    build: .
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql+psycopg://ai:ai@postgres:5432/intel
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j
      - MODEL_NAME=sentence-transformers/distiluse-base-multilingual-cased-v2
    volumes:
      - ./:/workspace
    working_dir: /workspace
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_started
    ports: ["8000:8000"]

  worker:
    build: .
    command: python -m app.workers.pipeline --ingest data/input
    environment:
      - DATABASE_URL=postgresql+psycopg://ai:ai@postgres:5432/intel
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j
      - MODEL_NAME=sentence-transformers/distiluse-base-multilingual-cased-v2
    volumes:
      - ./:/workspace
    working_dir: /workspace
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_started

volumes:
  pgdata:
  neo4jdata:
